CREATE TABLE IF NOT EXISTS landing_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_name VARCHAR(255),
    tagline TEXT,
    logo_path VARCHAR(255),
    favicon_path VARCHAR(255),
    hero_title VARCHAR(255),
    hero_subtitle TEXT,
    hero_image_path VARCHAR(255),
    about_story TEXT,
    features JSON,
    address TEXT,
    phone VARCHAR(50),
    email VARCHAR(255),
    operating_hours TEXT,
    social_facebook VARCHAR(255),
    social_instagram VARCHAR(255),
    social_tiktok VARCHAR(255),
    primary_color VARCHAR(10),
    secondary_color VARCHAR(10),
    font_style VARCHAR(50),
    layout_style VARCHAR(50),
    newsletter_enabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY idx_single_record (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;